services:
  #CUSTOMER MICROSERVICE
  customer-service:
    image: leonardocionchi/customer-service:latest
    #build:
      #context: ./customer-service
    container_name: customer-service
    ports:
      - "8102:9010"
    depends_on:
      - customer-postgres

  customer-postgres:
    image: postgres:latest
    container_name: customer-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer

  #BORROWING MICROSERVICE
  borrowing-service:
    image: leonardocionchi/borrowing-service:latest
    container_name: borrowing-service
    ports:
      - "8103:8102"
    environment:
      - MONGO_URI=mongodb+srv://MongoDB:MongoDB@microservices.crf2stj.mongodb.net/BorrowingDB?retryWrites=true&w=majority

  #BOOK MICROSERVICE
  book-service:
    image: leonardocionchi/books-service:latest
    container_name: books-service
    ports:
      - "8104:3000"
    depends_on:
      - book-postgres

  book-postgres:
    image: postgres:latest
    container_name: book-postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book

    

