services:
  customer-service:
    image: leonardocionchi/customer-service:latest
    #build:
      #context: ./customer-service
    container_name: customer-service
    ports:
      - "8102:9010"
    depends_on:
      - customer-postgres

  customer-postgres:
    image: postgres:latest
    container_name: order-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer