customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - "8103:8103"
    depends_on:
      - postgres_db

    postgres_db:
      image: postgres:latest
      container_name: order-postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./order/dbinit.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres